version: 2
updates:
  -   package-ecosystem: npm
      directory: /
      schedule:
        interval: daily
      reviewers:
        - kzmshx
      labels:
        - dependencies
      versioning-strategy: auto
      pull-request-branch-name:
        separator: "-"